#! /bin/bash


main() {
	if [[ $1 == "install" ]]; then
		install $2 
	fi
    if [[ $1 == "sync" ]]; then
        sync
    fi 
	if [[ $1 == "build" ]];then
		build $2
	fi
    if [[ $1 == "help" ]];then 
        echo "Please run azura sync before using other functions"
    fi
    if [[ $1 == "update" ]];then 
        echo "UPDATING"
        update $2
    fi
    if [[ $1 == "upgrade" ]]; then 
        upgrade
    fi
    echo "Thanks for using Azura on Onyx, please report any feedback"
}

 
sync() {
    cd /var/cache/
    ls onyx
    if [[ $? != 0 ]]; then 
        git clone https://github.com/Delta-Azura/onyx.git
    else 
        cd onyx 
        git fetch origin 
        BEHIND=$(git rev-list HEAD..origin/main --count)
        if [[ $BEHIND -gt 0 ]]; then
            echo "$BEHIND commit(s) en retard"
            git pull
        fi
    fi
	ls /usr/bin/fakeroot
	if [[ $? != 0 ]]; then 
		echo "Fakeroot needs to be installed"
		exit
	fi
    ls /usr/bin/awk
    if [[ $? != 0 ]]; then
        echo "Awk isn't installed"
        exit
    fi 

}

build() { 
    package="$1"
    cd $package
	cat Pkgfile
	pwd
	echo "DEBUG package=[$package]"
	fakeroot pkgmk -d 2>&1
}

install() {
    package=$(ls $1/*cards*)
    conflict=$(pkgadd $package 2>&1)
	if [[ $? == 0 ]]; then 
		echo "SUCCESS"
	else
		echo $conflict
		echo $conflict | grep -- "-f"
        #up=$(pkginfo -d $package)
		if [[ $? == "0" ]]; then 
			read -p "Conflict with existing files detecting, do you want to overwrite ? : " answer 
			if [[ $answer == "y" ]]; then
				pkgadd -f /var/cache/onyx/$package
			fi
        else 
            read -p "The package is already installed, do you want to upgrade ? : " reponse
            if [[ $reponse == "y" ]]; then
            pkgadd -u /var/cache/onyx/$package
            fi
        fi 
    fi 
}

update() {
    init
    namepkg=$1
    check=$(pkginfo -d $1)
    if [[ $? != "0" ]]; then 
        echo "The package isn't installed, build and install it"
        exit
    fi
    verify=$(echo $check | grep Version | awk '{print $3}')
    collection=$(echo $check | grep Collection | awk '{print $3}')
    pushd /var/cache/onyx/$collection/$1
    source Pkgfile
    popd
    if [[ $version == $verify ]]; then 
        echo "$1 is up to date"
    else
    ##### MOVE THIS TO THE BUILD FUNCTION AND CHECK CONFIGURATION FUNCTION 
        if [[ $namepkg == "kernel" ]]; then
            cp /etc/azura.d/kernel/config /var/cache/onyx/core/kernel/
        fi
        build $1
    fi
}


upgrade() {
    init
    configuration
    namepkg=$(ls /var/lib/pkg/DB/)
    for i in $namepkg; do
        verify=$(pkginfo -d $i | awk '/^Version/{print $3}')
        #collection=$(pkginfo -d $i | awk '/^Collection/{print $3}')
        pathpkg=$(find /var/cache/onyx/ -name $i -type d)
        #pathpkg=$(cat $collection)
	echo $verify && echo $pathpkg
	version=$(source $pathpkg/Pkgfile && echo $version)
        if [[ $version == $verify ]]; then 
            echo "$i is up to date"
        else
            build $pathpkg
		
		install $pathpkg
        fi
    done 
}

configuration() {
    source /etc/azura.conf
}

main "$@"
