#! /bin/bash


main() {
	if [[ $1 == "install" ]]; then 
		install $2 
	fi
	echo "tamère" 
}
#main "$@"
 
init() {
    cd /var/cache/
    ls onyx
    if [[ $? != 0 ]]; then 
        git clone https://github.com/Delta-Azura/onyx.git
    else 
        cd onyx 
        git fetch origin 
        BEHIND=$(git rev-list HEAD..origin/main --count)
        if [[ $BEHIND -gt 0 ]]; then
            echo "$BEHIND commit(s) en retard"
            git pull
        fi
    fi

}

build() {
	echo $?
    init 
    package="$1"
    cd /var/cache/onyx/$package
    source Pkgfile
    for i in $makedepends; do 
        pkginfo -d $i 
        if [[ $? != 0 ]]; then
            echo "Makedepends aren't installed"
            depends1=$(find ../../* -name"$i" -type d)
            if [[ $? != 0 ]]; then 
                echo "The dependencies aren't in the repo"
                exit
            else
                install "$i"
            fi
        fi
    done 

    for i in $depends; do 
        pkginfo -d $i  
        if [[ $? != 0 ]]; then 
            echo "Dependencies aren't satisfied"
            makedepends1=$(find ../../* -name "$i" -type d) 
            if [[ $? != 0 ]]; then 
                echo "The dependencies aren't in the repo"
                exit
            else 
                install "$i"
            fi 
        fi
    done

    fakeroot pkgmk -d 
    if [[ $? == "0" ]]; then 
        echo "Build succeded, use pkgadd or pkgadd -u to install or update $package" 
    fi
}

install() {
    package=$(ls /var/cache/onyx/$1 | grep cards)
    pkgadd $package
    read -p "The package is already installed, do you want to upgrade ? : " reponse
    if [[ $reponse == "y" ]]; then
        pkgadd -u $package
    fi
}


main "$@"
