#! /bin/bash


main() {
	if [[ $1 == "install" ]]; then 
		install $2 
	fi
	if [[ $1 == "build" ]];then
		build $2
	fi
    if [[ $1 == "help" ]];then 
        echo "Azura is still being built, please be careful"
    fi
    if [[ $1 == "update" ]];then 
        echo "UPDATING"
        update $2
    fi
    if [[ $1 == "upgrade" ]]; then 
        upgrade 
    fi
    echo "Thanks for using Azura on Onyx, please report any feedback"
}

 
init() {
    cd /var/cache/
    ls onyx
    if [[ $? != 0 ]]; then 
        git clone https://github.com/Delta-Azura/onyx.git
    else 
        cd onyx 
        git fetch origin 
        BEHIND=$(git rev-list HEAD..origin/main --count)
        if [[ $BEHIND -gt 0 ]]; then
            echo "$BEHIND commit(s) en retard"
            git pull
        fi
    fi
	ls /usr/bin/fakeroot
	if [[ $? != 0 ]]; then 
		echo "Fakeroot needs to be installed"
		exit
	fi
    ls /usr/bin/awk
    if [[ $? != 0 ]]; then
        echo "Awk isn't installed"
        exit
    fi 

}

build() {
	echo $?
    init 
    package="$1"
    cd /var/cache/onyx/$package
    source Pkgfile
    for i in $makedepends; do 
        pkginfo -d $i 
        if [[ $? != 0 ]]; then
            echo "Makedepends aren't installed"
            depends1=$(find ../../* -name"$i" -type d)
            if [[ $? != 0 ]]; then 
                echo "The dependencies aren't in the repo"
                exit
            else
                install "$i"
            fi
        fi
    done 

    for i in $depends; do 
        pkginfo -d $i  
        if [[ $? != 0 ]]; then 
            echo "Dependencies aren't satisfied"
            makedepends1=$(find ../../* -name "$i" -type d) 
            if [[ $? != 0 ]]; then 
                echo "The dependencies aren't in the repo"
                exit
            else 
                install "$i"
            fi 
        fi
    done

    fakeroot pkgmk -d 
    if [[ $? == "0" ]]; then 
        echo "Build succeded, use pkgadd or pkgadd -u to install or update $package" 
    fi
}

install() {
    package=$(ls /var/cache/onyx/$1 | grep cards)
    conflict=$(pkgadd /var/cache/onyx/$1/$package 2>&1)
	if [[ $? == 0 ]]; then 
		echo "SUCCESS"
	else
		echo $conflict
		echo $conflict | grep -- "-f"
        #up=$(pkginfo -d $package)
		if [[ $? == "0" ]]; then 
			read -p "Conflict with existing files detecting, do you want to overwrite ? : " answer 
			if [[ $answer == "y" ]]; then
				pkgadd -f /var/cache/onyx/$1/$package
			fi
        else 
            read -p "The package is already installed, do you want to upgrade ? : " reponse
            if [[ $reponse == "y" ]]; then
            pkgadd -u /var/cache/onyx/$1/$package
            fi
        fi 
    fi 
}

update() {
    init
    namepkg=$1
    check=$(pkginfo -d $1)
    if [[ $? != "0" ]]; then 
        echo "The package isn't installed, build and install it"
        exit
    fi
    verify=$(echo $check | grep Version | awk '{print $3}')
    collection=$(echo $check | grep Collection | awk '{print $3}')
    pushd /var/cache/onyx/$collection/$1
    source Pkgfile
    popd
    if [[ $version == $verify ]]; then 
            echo "$1 is up to date"
    else
            build $1
    fi
}


upgrade() {
    init
    namepkg=$(ls /var/lib/pkg/DB/)
    for i in $namepkg; do
        check=$(pkginfo -d $i)
        verify=$(echo $check | grep Version | awk '{print $3}')
        collection=$(echo $check | grep Collection | awk '{print $3}')
        pushd /var/cache/onyx/$collection/$i
        source Pkgfile
        popd
        if [[ $version == $verify ]]; then 
            echo "$i is up to date"
        else
            if [[ $namepkg == "kernel" ]]; then 
                mv /etc/azura.d/kernel/config /var/cache/onyx/kernel/config
            fi 
            build $i
        fi
    done 
}

configuration() {
    source /etc/azura.conf
}

main "$@"
